version: '3.4'
services:
    nginx:
        image: nginx:1.13.6-alpine
        hostname: nginx
        ports:
            - 3000:80/tcp
        networks:
            chanzhieps:
                aliases:
                    - nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == manager
    chanzhieps:
        image: chanzhieps:6.7.1
        hostname: chanzhieps
        networks:
            chanzhieps:
                aliases:
                    - chanzhieps
        environment:
            - CHANZHI_DB_HOST=mysql
            - CHANZHI_DB_USER=root
            - CHANZHI_DB_PASS=root
        volumes:
            - ./www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 3
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == manager
    mysql:
        image: mysql:5.7.20
        hostname: mysql
        networks:
            chanzhieps:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    chanzhieps:
        external: true
