version: '3.4'
services:
    server:
        image: cobbler:2.8.2
        networks:
            cobbler:
        volumes:
            - tftpboot:/var/lib/tftpboot
            - log:/var/log/cobbler
            - www:/var/www/cobbler
            - lib:/var/lib/cobbler
            - etc:/etc/cobbler
            - /mnt/iso:/iso:ro
        environment:
            - Cobbler_SERVER_IP=10.0.8.254
            - Cobbler_NEXT_SERVER_IP=10.0.8.254
            - Cobbler_PASSWORD=root
            - Cobbler_DHCP_SUBNET=10.0.0.0
            - Cobbler_DHCP_ROUTER=10.0.1.1
            - Cobbler_DHCP_DNS=114.114.114.114
            - Cobbler_DHCP_RANGE="10.0.8.100 10.0.8.200"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.labels.cobbler == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
volumes:
    tftpboot:
        driver: local
    log:
        driver: local
    www:
        driver: local
    lib:
        driver: local
    etc:
        driver: local

networks:
    cobbler:
        external:
            name: "host"