version: '3.4'
services:
    jenkins:
        image: daocloud.io/buxiaomo/jenkins:2.89.3
        ports:
            - 80:8080/tcp
        environment:
            - LC_ALL=C.UTF-8
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /mnt/nfs/jenkins/data:/var/jenkins:rw
        networks:
            jenkins:
                aliases:
                    - jenkins
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
networks:
    jenkins:
      external: true
