apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - env:
        - name: LC_ALL
          value: C.UTF-8
        image: daocloud.io/buxiaomo/jenkins:2.89.3
        name: jenkins
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: jenkins-claim0
          readOnly: true
        - mountPath: /var/jenkins
          name: jenkins-claim1
      restartPolicy: Always
      volumes:
      - name: jenkins-claim0
        persistentVolumeClaim:
          claimName: jenkins-claim0
          readOnly: true
      - name: jenkins-claim1
        persistentVolumeClaim:
          claimName: jenkins-claim1
status: {}
