version: '3.4'
services:
    node01:
        image: kafka:latest
        networks:
            kafka:
        environment:
            KAFKA_CONFIG: |
                broker.id=1
                advertised.host.name=10.211.55.14
                advertised.port=9092
                zookeeper.connect=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
                num.partitions=6
                delete.topic.enable=true
                auto.create.topics.enable=true
                log.cleanup.policy=delete
                host.name=10.211.55.14
        volumes:
            - /var/lib/kafka:/var/lib/kafka:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            resources:
                limits:
                    cpus: '4'
                    memory: 4G
                reservations:
                    cpus: '2'
                    memory: 2G
            placement:
                constraints:
                    - node.labels.kafka.node01 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node02:
        image: kafka:latest
        networks:
            kafka:
        environment:
            KAFKA_CONFIG: |
                broker.id=2
                advertised.host.name=10.211.55.14
                advertised.port=9092
                zookeeper.connect=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
                num.partitions=6
                delete.topic.enable=true
                auto.create.topics.enable=true
                log.cleanup.policy=delete
                host.name=10.211.55.14
        volumes:
            - /var/lib/kafka:/var/lib/kafka:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            resources:
                limits:
                    cpus: '4'
                    memory: 4G
                reservations:
                    cpus: '2'
                    memory: 2G
            placement:
                constraints:
                    - node.labels.kafka.node02 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    node03:
        image: kafka:latest
        networks:
            kafka:
        environment:
            KAFKA_CONFIG: |
                broker.id=3
                advertised.host.name=10.211.55.14
                advertised.port=9092
                zookeeper.connect=zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
                num.partitions=6
                delete.topic.enable=true
                auto.create.topics.enable=true
                log.cleanup.policy=delete
                host.name=10.211.55.14
        volumes:
            - /var/lib/kafka:/var/lib/kafka:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: stop-first
            resources:
                limits:
                    cpus: '4'
                    memory: 4G
                reservations:
                    cpus: '2'
                    memory: 2G
            placement:
                constraints:
                    - node.labels.kafka.node03 == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

networks:
    kafka:
        external:
            name: "host"